task: puzzle_sudoku_n4_12
fewshot_split: null
validation_split: null
dataset_path: json
dataset_name: null
dataset_kwargs:
  split: train
  data_files: /data/dInfer/ParallelBench/dataset/parallel_bench/data/output/test/puzzle/sudoku_n4_12.jsonl
process_docs: !function adapter.process_docs
doc_to_text: !function adapter.doc_to_text
doc_to_target: !function adapter.doc_to_target
metric_list:
  - metric: !function adapter.sudoku_score_metric
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "\n\n"
    - "</s>"
    - "<|im_end|>"
  do_sample: false
  temperature: 0.0
metadata:
  version: 1.0

