task: waiting_line_copy
dataset_path: json
dataset_name: null
dataset_kwargs:
  data_files: /data/dInfer/ParallelBench/dataset/parallel_bench/data/output/test/waiting_line/copy.jsonl
  # Set config_name to help process_docs infer task name
  config_name: waiting_line/copy
process_docs: !function adapter.process_docs
doc_to_text: !function adapter.doc_to_text
doc_to_target: !function adapter.doc_to_target
metric_list:
  - metric: !function adapter.list_match_score_metric
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "\n\n"
    - "</s>"
    - "<|im_end|>"
  do_sample: false
  temperature: 0.0
metadata:
  version: 1.0

