tag:
  - math_word_problems
task: minerva_math_algebra_llada_mini
dataset_path: EleutherAI/hendrycks_math
process_docs: !function utils.process_docs
dataset_name: algebra
output_type: generate_until
training_split: train
test_split: test
doc_to_text: !function utils.doc_to_text
process_results: !function utils.process_results
doc_to_target: "{{answer if few_shot is undefined else solution}}"
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_samples
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
  - metric: math_verify
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "Problem:"
  do_sample: false
  temperature: 0
repeats: 1
num_fewshot: 4
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "\\\\boxed\\{([^}]+)\\}"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(-?[$0-9.,]{2,})|(-?[0-9]+)"
      - function: "take_first"
metadata:
  version: 3.0

